// Code generated by templ - DO NOT EDIT.

// templ: version: v0.3.898
package views

//lint:file-ignore SA4006 This context is only used if a nested component is present.

import "github.com/a-h/templ"
import templruntime "github.com/a-h/templ/runtime"

func Main() templ.Component {
	return templruntime.GeneratedTemplate(func(templ_7745c5c3_Input templruntime.GeneratedComponentInput) (templ_7745c5c3_Err error) {
		templ_7745c5c3_W, ctx := templ_7745c5c3_Input.Writer, templ_7745c5c3_Input.Context
		if templ_7745c5c3_CtxErr := ctx.Err(); templ_7745c5c3_CtxErr != nil {
			return templ_7745c5c3_CtxErr
		}
		templ_7745c5c3_Buffer, templ_7745c5c3_IsBuffer := templruntime.GetBuffer(templ_7745c5c3_W)
		if !templ_7745c5c3_IsBuffer {
			defer func() {
				templ_7745c5c3_BufErr := templruntime.ReleaseBuffer(templ_7745c5c3_Buffer)
				if templ_7745c5c3_Err == nil {
					templ_7745c5c3_Err = templ_7745c5c3_BufErr
				}
			}()
		}
		ctx = templ.InitializeContext(ctx)
		templ_7745c5c3_Var1 := templ.GetChildren(ctx)
		if templ_7745c5c3_Var1 == nil {
			templ_7745c5c3_Var1 = templ.NopComponent
		}
		ctx = templ.ClearChildren(ctx)
		templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 1, "<html><head><script src=\"https://unpkg.com/htmx.org@2.0.1\"></script><script src=\"https://unpkg.com/htmx.org@1.9.12/dist/ext/ws.js\"></script><style>\n    * {\n      margin: 0;\n      padding: 0;\n      box-sizing: border-box;\n    }\n\n    body {\n      zoom: 15%;\n      transform: translateX(19%) translateY(19%);\n      overflow: hidden;\n    }\n\n    .scene {\n      position: absolute;\n      transform-style: preserve-3d;\n      margin: 0;\n      overflow-scroll: none;\n      transform: translateX(-40vw) translateY(-40vh) rotate3d(1,0,0,20deg);\n    }\n    .stats {\n      position: relative;\n      left: 0px;\n      top: 0px;\n      color: red;\n      z-index: 2;\n      transform: translateX(-50vw) translateY(-50vh);\n      width: 100vw;\n      height: 200px;\n      font-size: 50px;\n    }\n    .crosshair {\n      position: static;\n      color: white;\n      font-size: 50px;\n      font-weight: bold;\n      text-align: center;\n      line-height: 2000px;\n\n      transform: scale3d(100,100,100) translate3d(0,1px,0) rotate3d(1,0,0,90deg);\n      background-image: radial-gradient(#00BFFF, white, blue);\n      width: 2000px;\n      height: 2000em;\n      transform-style: preserve-3d;\n    }\n\n  </style></head><body><div hx-ext=\"ws\" ws-connect=\"/ws\"><div hx-trigger=\"load, htmx:wsOpen dely:2s\" id=\"player_init\" ws-send></div><div id=\"scene_transform\"></div><div id=\"scene\" class=\"scene\"></div><div id=\"player_controls\">")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Err = PlayerControls().Render(ctx, templ_7745c5c3_Buffer)
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 2, "</div></div></body></html>")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		return nil
	})
}

var _ = templruntime.GeneratedTemplate
